### ISSUE TITLE
Update version of `config.guess` used by `ConfigureMake`

### ISSUE THREAD

**Issue by ocaisa** [easybuilders/easybuild-easyblocks#2826] opened 2022-11-11 09:13 UTC
The version of `config.guess` that we use is from 2018. Looking at https://git.savannah.gnu.org/cgit/config.git/log/config.guess it is probably important that we update it for RISC-V support

**Comment by boegel** [comment] 2022-11-11 12:20
I agree we should use a more recent `config.guess`, but hopefully this won't lead to nasty surprises, since it will be difficult to ensure we don't introduce any regressions by doing so...

We should also use a `cgit` download URL, see https://git.savannah.gnu.org/cgit/config.git/commit/config.guess?id=888c8e3d5f7bf7464bba83aaf54304a956eefa60

**Comment by boegel** [comment] 2022-11-11 12:21
In addition, we should check if we should also download `config.sub` alongside `config.guess`

**Comment by ocaisa** [comment] 2022-11-11 13:04
I'm thinking about adding some of the commit id as part of the `config.guess` filename. That way every version of EB will always use the same version of the file. Right now, if you we update the eb version and then someone uses an older version of eb to install something you will get an error about the checksum/dates not matching.

**Comment by ocaisa** [comment] 2022-11-11 13:17
I looked into `config.sub` and according to the docs:
> `configure` recognizes short aliases for many system types; for example, `decstation` can be used instead of `mips-dec-ultrix4.2`. `configure` runs a script called `config.sub` to canonicalize system type aliases.

It's a good bit of work to add `config.sub` and I don't see it having any value for us since we are getting the system type from `config.guess`

**Comment by boegel** [comment] 2023-10-06 06:37
> I'm thinking about adding `CONFIG_GUESS_VERSION` as part of the `config.guess` filename. That way every version of EB will always use the same version of the file. Right now, if you we update the `eb` version and then someone uses an older version of `eb` to install something you will get an error about the checksum/dates not matching.

That's only true for the `develop` branch (if you go back to an old commit in `develop`), since there's a separate `config.guess` downloaded for every EasyBuild version.

**Comment by boegel** [comment] 2023-10-06 07:02
fixed in #3013

**Closed by boegel** 2023-10-06 07:02 UTC
Labels: update, EasyBuild-5.0
