### ISSUE TITLE
Components of EasyBlock Bundle cannot be patched

### ISSUE THREAD

**Issue by renatopancheri** [easybuilders/easybuild-easyblocks#1331] opened 2017-12-22 11:12 UTC
I had to patch some components of X11 but the patch did not apply at all
Patch step is run for bundle components:
bundle.py:147  `for step_name in ['patch', 'configure', 'build', 'install']:`
I solved this issue by adding fetch step, it seams like fetch step actually populates the array of the patches for patch step or something like that

**Comment by boegel** [comment] 2017-12-22 11:18
@renatopancheri Thanks for the bug report and the proposed fix, I'll try and look into this for EasyBuild v3.5.1.

**Comment by Flamefire** [comment] 2019-12-19 10:17
This could be caused by https://github.com/easybuilders/easybuild-easyblocks/issues/1893

**Comment by boegel** [comment] 2020-01-04 22:34
The `libxcb` component in recent `X11` easyconfigs (which use `Bundle`) has a patch, so this issue is no longer valid (looks like this was fixed in #1369).

**Closed by boegel** 2020-01-04 22:34 UTC
Labels: bug report
