### ISSUE TITLE
Bundle easyblock doesn't inject checksums

### ISSUE THREAD

**Issue by deniskristak** [easybuilders/easybuild-easyblocks#2392] opened 2021-04-23 11:50 UTC
related to https://github.com/easybuilders/easybuild-framework/issues/3403
`eb --inject-checksums` doesnt work for easyconfig with easyblock `Bundle` specified..
not even with `--force` option

**Comment by boegel** [comment] 2021-04-28 14:34
closing as duplicate of https://github.com/easybuilders/easybuild-framework/issues/3403

**Closed by boegel** 2021-04-28 14:34 UTC
Labels: bug report
