### ISSUE TITLE
PGI doesn't accept "-pthread" switch

### ISSUE THREAD

**Issue by MisterFruits** [easybuilders/easybuild-easyblocks#1493] opened 2018-08-31 12:40 UTC
I'm trying to compile OpenMPI 2.1.2 with PGI 18.4 and I stumbled upon a pgi error saying that it doen't accept -pthread switch

After few research I saw this thread: https://www.pgroup.com/userforum/viewtopic.php?t=5253&sid=93356f57a47eee097b569b79bc744676
basicaly PGI accept -lpthread instead
and one solution for PGI to accept -pthread would be to modify the siterc in $PGI_INSTALL/bin/siterc

**Comment by boegel** [comment] 2018-09-01 15:49
relevant (but still open): https://github.com/open-mpi/ompi/issues/2331

**Comment by boegel** [comment] 2018-09-01 15:51
And it looks like this problem has been around for a while, see http://users.open-mpi.narkive.com/wJDqFkNg/ompi-users-pgi-9-0-lpthread-instead-of-pthread .

Makes you wonder why PGI just didn't start accepting `-pthread` and translate it to `-lpthread` internally to get it over with, but fine... :)

**Comment by boegel** [comment] 2018-09-04 19:10
@MisterFruits I'm having trouble reproducing this problem...

I was trying to so I could test the fix you contributed in https://github.com/easybuilders/easybuild-easyblocks/pull/1494, but I'm not seeing any issues w.r.t. `-pthread` even though the `PGI/18.4-GCC-6.4.0-2.28` was not installed with the updated `PGI easyblock...

Any idea what I'm overlooking? Can you share the easyconfig file you were using here?

**Comment by akesandgren** [comment] 2018-09-04 19:27
@boegel The problem exists, believe me :-) Anything you build with pgi and an openmpi that has --with-pmi=path-to-slurm and/or --with-slurm=the-same should fail, unless you have already patched libpmi.la and libslurm.la

**Comment by boegel** [comment] 2018-09-04 19:57
@akesandgren Ah, it's the SLURM aspect then... Will try on a SLURM cluster, thanks.

**Comment by MisterFruits** [comment] 2018-09-04 20:58
I confirm that I was compiling openmpi  2.1.2 with PGI 18.4 using some slurm config-opts (among others) but I haven't the easyconfig file available right now

**Comment by boegel** [comment] 2018-09-11 07:33
Fixed in #1494, thanks @MisterFruits!

**Closed by boegel** 2018-09-11 07:33 UTC
Labels: problem report
