### ISSUE TITLE
EB_PYTHON startup behaviour

### ISSUE THREAD

**Issue by ghferrari** [easybuilders/easybuild-easyblocks#2078] opened 2020-06-11 13:45 UTC
The documentation at https://easybuild.readthedocs.io/en/latest/Python-2-3-compatibility.html?#controlling-which-python-command-easybuild-will-use-via-eb-python suggests that one can control which version of Python EasyBuild will use by setting EB_PYTHON.

Since https://github.com/easybuilders/easybuild-easyblocks/commit/40b76bef5a1f4f149e0c13cce913c051b54da5a3 running `module load EasyBuild` will now overwrite any existing EB_PYTHON environment variable.

While it is still possible to configure EB_PYTHON after running `module load EasyBuild`, it is no longer possible to configure EB_PYTHON first (e.g. in one's shell startup), since it is overwritten when EasyBuild loads.

If this is the desired behaviour then it should be documented. If this is not the desired behaviour, then it is a bug.

**Comment by boegel** [comment] 2020-06-12 08:04
The `EasyBuild` module sets `$EB_PYTHON` because the Python version that should be used for running EasyBuild is known during the installation. It's a mechanism to prevent that the EasyBuild installation breaks if it was installed with `python3` for example, and then a `python` command gets added to the system afterwards.

Setting `$EB_PYTHON` manually is mostly interesting for EasyBuild installations that are done manually via `pip install` or by cloning the repositories and updated `$PYTHONPATH`, I guess.

I'm happy to try and clarify this in the documentation. Do you have any suggestions on the wording we could use for  that?

**Comment by ghferrari** [comment] 2020-06-12 12:06
Hi again,

The current documentation strongly suggests that EB_PYTHON is used for run-time configuration of which python binary to use.

- The example given in the documentation shows setting EB_PYTHON after EasyBuild has already been installed.
- The values `python2` `python3` only seem to make sense as runtime configuration options. If they were intended to store a reference to a particular python binary so that path changes could not alter it, then they would need to store a full path.

In short, the current documentation doesn't suggest at all that EB_PYTHON is an install-time configuration - it suggests the opposite.

Furthermore, if it were true EB_PYTHON needs to be set once at install-time and can't change after that, it would be surprising that it took until version 4.1.2 for the developers to become aware of that.

Finally, what is the reason for wanting to keep the version of Python fixed to what was used at install time? Will EasyBuild break if run with a different version of Python than was used at install time? If the reason is just to prevent surprises to the user in case of path changes, then I would think most EasyBuild users are sufficiently expert not to find that problematic.

Runtime configuration of which python to use is a useful feature since e.g. other packages that work with EasyBuild such as GC3Pie may require particular versions of python and this might change over time.

Many thanks,

Geoff

**Comment by ocaisa** [comment] 2020-07-28 07:56
Ok, let's try to come to an understanding on this so we can move towards closing this issue. To get things straight, `EB_PYTHON` is indeed used for runtime configuration of EasyBuild, i.e., if I run
```
EB_PYTHON=foo eb ...
```
eb will try to use `foo` for Python when running. What you asking for is something different, you are asking that if you have set `EB_PYTHON` then loading the EasyBuild module should not override that setting. As far as I can tell, there is no explicit way to allow for this behaviour in a module file (unless you use lua/tcl features as opposed to module tool features).

The other option is to have an additional environment variable that takes lower precedence than `EB_PYTHON` and use that in the EasyBuild module instead, something like `EB_INSTALLPYTHON`. That would not require changes in the documentation but will require PRs in the framework (to respect the variable in the `eb` script) and the easyblock repo (to set the variable instead of `EB_PYTHON`)

**Comment by ghferrari** [comment] 2020-07-28 08:19
Thank you, @ocaisa. I agree with the essentials of your proposal.

**Comment by ocaisa** [comment] 2020-07-28 08:50
Addressed in https://github.com/easybuilders/easybuild-easyblocks/pull/2109 and https://github.com/easybuilders/easybuild-framework/pull/3394

**Comment by boegel** [comment] 2020-08-05 06:36
@ocaisa Wouldn't it be better to generate code in the module file that only sets `$EB_PYTHON` if that environment variable isn't defined yet, rather than setting it blindly like we are doing now?

That means we can't use `set_environment` directly, we'll have to wrap it in a condition, but that should be possible in Tcl/Lua I think?

Your suggestion of using an additional environment variable works too, but could lead to confusion I think...

**Comment by ocaisa** [comment] 2020-08-05 06:58
Isn't that overly complicated? You'll have to use TCL/lua rather than module functions (I checked Lmod last week). And how do you achieve the expected behaviour when unloading? To me it seemed like too much of a dance when there is a pretty trivial solution.

**Comment by ocaisa** [comment] 2020-09-02 07:53
@boegel Add comments and clarifications to https://github.com/easybuilders/easybuild-framework/pull/3394 and #2109 

I still need convincing that the alternative solution is worth the acrobatics, this approach is, to me, straightforward: the EB installation sets a private variable to record what Python installation was used for when installing it.

**Comment by ocaisa** [comment] 2020-09-02 12:06
The framework part of this has been moved to https://github.com/easybuilders/easybuild-framework/pull/3394

**Closed** 2020-09-25 08:43 UTC
Labels: documentation, problem report
